require("ovorange.base")
require("ovorange.plugins")
require("ovorange.colorscheme")
require("ovorange.fcitx")
require("ovorange.plugins.nvim-tree")
require("ovorange.plugins.lualine")
require("ovorange.plugins.bufferline")
